export const QUERY_KEY = {
  //mutations
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",

  //queries
  GET_PEOPLE: "GET_PEOPLE",
  GET_PEOPLE_BY_ID: "GET_PEOPLE_BY_ID",
  LOGOUT: "LOGOUT",
  REFRESH: "REFRESH",
  GET_SERVICE_LIST: "GET_SERVICE_LIST",
  GET_APPLICATION_SLO_LIST: "GET_APPLICATION_SLO_LIST",
  GET_APPLICATION_ACCESS_LIST: "GET_APPLICATION_ACCESS_LIST",
  GET_AWS_INTEGRATIONS_BY_PROJECTID: "GET_AWS_INTEGRATIONS_BY_PROJECTID",
  GET_GREMLIN_INTEGRATIONS_BY_PROJECTID:
    "GET_GREMLIN_INTEGRATIONS_BY_PROJECTID",
  GET_AWS_INTEGRATIONS_BY_APPLICATIONID:
    "GET_AWS_INTEGRATIONS_BY_APPLICATIONID",
  GET_GITHUB_INTEGRATIONS_BY_PROJECTID: "GET_GITHUB_INTEGRATIONS_BY_PROJECTID",
  GET_GITHUB_INTEGRATIONS_BY_APPLICATIONID:
    "GET_GITHUB_INTEGRATIONS_BY_APPLICATIONID",

  // Project
  GET_PROJECTS: "GET_PROJECTS",
  GET_PROJECT_DETAILS: "GET_PROJECT_DETAILS",
  CREATE_PROJECT: "CREATE_PROJECT",
  CHECK_PROJECT_NAME: "CHECK_PROJECT_NAME",
  GET_EMAIL_NOTIFICATION: "GET_EMAIL_NOTIFICATION",

  // Application
  GET_APPLICATIONS: "GET_APPLICATIONS",
  GET_APPLICATION_DETAILS: "GET_APPLICATION_DETAILS",

  //users
  GET_USERS: "GET_USERS",
  GET_USER_ROLES: "GET_USER_ROLES",
  GET_ACCESS_LIST: "GET_ACCESS_LIST",
  GET_USER_PROFILE: "GET_USER_PROFILE",

  //team
  GET_TEAMS: "GET_TEAMS",
  GET_TEAM_DETAILS: "GET_TEAM_DETAILS",

  // Infra
  GET_INFRA_RESOURCES: "GET_INFRA_RESOURCES",
  GET_INFRA_RESOURCE_LIST: "GET_INFRA_RESOURCE_LIST",
  GET_RESILIENCY_POLICY_LIST: "GET_RESILIENCY_POLICY_LIST",
  GET_LIST_RESOURCE_GROUP: "GET_LIST_RESOURCE_GROUP",

  // Diagnostics
  GET_DIAGNOSTICS_REPORT: "GET_DIAGNOSTICS_REPORT",
  GET_DIAGNOSTICS_VERSIONS_LIST: "GET_DIAGNOSTICS_VERSIONS_LIST",

  //Codescan
  FETCH_CODESCAN_DASHBOARD: "FETCH_CODESCAN_DASHBOARD",
  FETCH_CODE: "FETCH_CODE",
  RESCAN: "RESCAN",
  TOTAL_VERSIONS: "TOTAL_VERSIONS",
  CODE_SCAN: "CODE_SCAN",

  //Dashboard
  FETCH_DASHBOARD: "FETCH_DASHBOARD",
  FETCH_APP_DASHBOARD_RECOMMENDATION_DTLS_TABLE:
    "FETCH_APP_DASHBOARD_RECOMMENDATION_DTLS_TABLE",
  FETCH_APP_RELIABILITY_SCORE: "FETCH_APP_RELIABILITY_SCORE",
  FETCH_APP_RELIABILITY_POSTURE: "FETCH_APP_RELIABILITY_POSTURE",
  GET_PORTFOLIO_GRAPH_DATA: "GET_PORTFOLIO_GRAPH_DATA",
  GET_PORTFOLIO_DETAILS: "GET_PORTFOLIO_DETAILS",
  GET_PORTFOLIO_RECOMMENDATION: "GET_PORTFOLIO_RECOMMENDATION",

  //Experiments
  GET_SCENARIO_LISTS: "GET_SCENARIO_LISTS",
  GET_CHAOS_DATA: "GET_CHAOS_DATA",
  GET_CHAOS_VERSIONS: "GET_CHAOS_VERSIONS",
  RERUN_CHAOS_SCAN: "RERUN_CHAOS_SCAN",
  GET_CONFIG_FILE: "GET_CONFIG_FILE",
  GET_CHAOS_AGENTS: "GET_CHAOS_AGENTS",
  GET_ACTIVE_CHAOS_AGENTS: "GET_ACTIVE_CHAOS_AGENTS",
  GET_ACTIVE_HEALTHCHECKS: "GET_ACTIVE_HEALTHCHECKS",

  // Drift Assist
  GET_DRIFT_ANALYSES: "GET_DRIFT_ANALYSES",
  GET_DRIFT_ANALYSIS_DETAILS: "GET_DRIFT_ANALYSIS_DETAILS",
  CREATE_DRIFT_ANALYSIS: "CREATE_DRIFT_ANALYSIS",
  START_DRIFT_ANALYSIS: "START_DRIFT_ANALYSIS",
  DELETE_DRIFT_ANALYSIS: "DELETE_DRIFT_ANALYSIS",
  CONNECT_AWS: "CONNECT_AWS",
  GET_S3_BUCKETS: "GET_S3_BUCKETS",
  GET_STATE_FILES: "GET_STATE_FILES",
  ANALYZE_BUCKET: "ANALYZE_BUCKET",
  LIST_STORED_ANALYSES: "LIST_STORED_ANALYSES",
  GET_STORED_ANALYSIS: "GET_STORED_ANALYSIS",
  
  // Drift Assist Integration Management
  CREATE_DRIFT_ASSIST_SECRET: "CREATE_DRIFT_ASSIST_SECRET",
  LIST_DRIFT_ASSIST_SECRETS: "LIST_DRIFT_ASSIST_SECRETS",
  GET_DRIFT_ASSIST_SECRET: "GET_DRIFT_ASSIST_SECRET",
  GET_SECRET_VALUES: "GET_SECRET_VALUES",
  CONNECT_AWS_WITH_INTEGRATION: "CONNECT_AWS_WITH_INTEGRATION",
};
